script_args:
  dataset_name: json
  dataset_kwargs:
    data_files:
      train: /home/x-cli32/chaohan/projects/open-r1/src/open_r1/SPLLM/processed_data/train.jsonl
      validation: /home/x-cli32/chaohan/projects/open-r1/src/open_r1/SPLLM/processed_data/validation.jsonl
  dataset_train_split: train
  dataset_test_split: validation

training_args:
  output_dir: /home/x-cli32/chaohan/projects/open-r1/test_sft_output_spllm
  per_device_train_batch_size: 2
  num_train_epochs: 1
  learning_rate: 1e-5
  logging_steps: 1
  eval_strategy: steps
  eval_steps: 1
  max_seq_length: 512
  bf16: true
  gradient_checkpointing: true
  remove_unused_columns: false
  report_to: none

model_args:
  model_type: spllm
  model_name_or_path: Qwen/Qwen3-1.7B
  protein_model_name: facebook/esm2_t12_35M_UR50D
  text_model_finetune: true
  protein_model_finetune: false
  max_length_protein: 70
  trust_remote_code: true